[env:cardputer-adv]
platform = espressif32@6.9.0
board = m5stack-stamps3
framework = arduino

lib_deps =
    m5stack/M5Cardputer@^1.1.1
    earlephilhower/ESP8266Audio@1.9.7

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_RUNNING_CORE=0

build_unflags =
    -DARDUINO_RUNNING_CORE=1

monitor_speed = 115200
